from typing import List
from app.models import CurriculumModule, LabTask

CURRICULUM_MODULES: List[CurriculumModule] = [
    CurriculumModule(
        id="mod-1",
        title="1. Antigravity Overview & CLI Setup",
        description="Learn the fundamentals of Google Antigravity (AGY), installation via agy CLI, and workspace initialization.",
        icon="fa-rocket",
        estimated_time="10 mins",
        labs=[
            LabTask(
                id="mod-1-lab-1",
                title="Lab 1.1: Verify AGY Installation & Environment",
                instruction="Check your installed Antigravity CLI version and review active workspace permissions.",
                code_template="# Run AGY version check in terminal:\nagy --version\n\n# Check active workspace settings:\nagy status",
                explanation="The `agy` CLI provides seamless control over workspace sandboxes, agent sessions, and configuration settings.",
            ),
            LabTask(
                id="mod-1-lab-2",
                title="Lab 1.2: Workspace Architecture & Subfolder Scoping",
                instruction="Configure your workspace rules so new applications are created in dedicated subdirectories.",
                code_template="# Structure rule in .agents/GEMINI.md:\n# - Always create dedicated root subfolders for new projects\n# - Store technical specs inside the scoped folder",
                explanation="Keeping applications scoped inside subfolders prevents workspace pollution and maintains clean build boundaries.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-2",
        title="2. Interactive Slash Commands",
        description="Master slash commands to direct long-running goals, schedule timers, conduct design interviews, and persist behaviors.",
        icon="fa-terminal",
        estimated_time="15 mins",
        labs=[
            LabTask(
                id="mod-2-lab-1",
                title="Lab 2.1: Requirements Alignment with /grill-me",
                instruction="Use `/grill-me` to initiate a structured design interview with Antigravity before building complex features.",
                code_template="/grill-me",
                explanation="The `/grill-me` command explores design choices branch-by-branch, resolving ambiguity and producing specs.",
            ),
            LabTask(
                id="mod-2-lab-2",
                title="Lab 2.2: Autonomous Goal Execution with /goal",
                instruction="Trigger `/goal` for overnight or multi-step tasks requiring relentless agent execution.",
                code_template="/goal Build a full test suite with 100% code coverage for the auth module.",
                explanation="`/goal` instructs Antigravity to stay active and iterate autonomously until all verification criteria pass.",
            ),
            LabTask(
                id="mod-2-lab-3",
                title="Lab 2.3: Crons & Reminders with /schedule",
                instruction="Schedule background health checks or reminders using `/schedule`.",
                code_template="/schedule Cron='*/15 * * * *' Prompt='Check staging deployment health and log metrics'",
                explanation="`/schedule` creates non-blocking background cron tasks or timers without keeping standard threads asleep.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-3",
        title="3. Agent Rules & Personas (AGENTS.md)",
        description="Define structured team personas (@pm, @coder, @qa) and strict project guardrails in .agents/AGENTS.md.",
        icon="fa-users-cog",
        estimated_time="15 mins",
        labs=[
            LabTask(
                id="mod-3-lab-1",
                title="Lab 3.1: Defining the Tri-Persona Hierarchy",
                instruction="Write persona definitions for @pm (specs), @coder (implementation), and @qa (testing) in .agents/AGENTS.md.",
                code_template="""# My AI Development Team

## Product Manager (@pm)
- Role: Translates user ideas into granular, flawless technical specifications.
- Behavior: Strict and detail-oriented. Must verify requirements before code is written.

## Engineer (@coder)
- Role: Writes exceptionally clean, production-ready Python or JavaScript code.
- Behavior: Strictly adheres to the spec generated by @pm.

## Quality Assurance (@qa)
- Role: Reviews generated code, writes test suites, and runs validation loops.
- Behavior: Reports explicit error tracebacks back to @coder.""",
                explanation="Explicit team roles enforce separation of concerns and prevent hallucinated unrequested code changes.",
            ),
            LabTask(
                id="mod-3-lab-2",
                title="Lab 3.2: Setting Strict Environment Guardrails",
                instruction="Add explicit constraints for virtual environments, typed code, and black formatting.",
                code_template="""# Environment Isolation & Rules
- Virtual environment check: python3 -m venv .venv
- Activation prefix: source .venv/bin/activate && ...
- Strict typed Python 3.11+ and black formatting before completion.""",
                explanation="Strict constraints in `GEMINI.md` prevent global package pollution and guarantee code quality.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-4",
        title="4. Custom Skills System (SKILL.md)",
        description="Package reusable workflows, prompts, and script assets into modular Skills.",
        icon="fa-cubes",
        estimated_time="20 mins",
        labs=[
            LabTask(
                id="mod-4-lab-1",
                title="Lab 4.1: Writing a Skill frontmatter and instructions",
                instruction="Create a `SKILL.md` file with valid YAML frontmatter specifying `name` and `description`.",
                code_template="""---
name: code-auditor
description: Performs security and style analysis over modified files.
---

# Code Auditor Instructions
1. Inspect modified python files using `view_file`.
2. Search for unhandled exceptions or hardcoded secrets.
3. Report findings with severity ratings (HIGH, MED, LOW).""",
                explanation="Skills extend Antigravity capabilities and can be triggered automatically when relevant tasks arise.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-5",
        title="5. Model Context Protocol (MCP) Integration",
        description="Connect external data sources, database clusters, and web services using MCP servers.",
        icon="fa-network-wired",
        estimated_time="20 mins",
        labs=[
            LabTask(
                id="mod-5-lab-1",
                title="Lab 5.1: Configuring an MCP Server Manifest",
                instruction="Define a PostgreSQL or AlloyDB server in `mcp.json` with lazy-loaded tools.",
                code_template="""{
  "mcpServers": {
    "alloydb-postgresql": {
      "command": "python3",
      "args": ["-m", "mcp_server_alloydb"],
      "env": {
        "DB_HOST": "localhost"
      }
    }
  }
}""",
                explanation="MCP servers allow Antigravity agents to safely interact with external systems and databases.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-6",
        title="6. Subagent Orchestration & Messaging",
        description="Spawn specialized subagents concurrently and communicate via peer messaging.",
        icon="fa-sitemap",
        estimated_time="25 mins",
        labs=[
            LabTask(
                id="mod-6-lab-1",
                title="Lab 6.1: Spawning Subagents with invoke_subagent",
                instruction="Invoke research or coding subagents concurrently using `invoke_subagent`.",
                code_template="""# Tool call example:
invoke_subagent(
    Subagents=[
        {
            "TypeName": "research",
            "Role": "Database Researcher",
            "Prompt": "Analyze database schema for performance bottlenecks.",
            "Model": "flash"
        }
    ]
)""",
                explanation="Subagents run in parallel with isolated contexts, speeding up research and heavy refactoring.",
            ),
            LabTask(
                id="mod-6-lab-2",
                title="Lab 6.2: Inter-Agent Communication with send_message",
                instruction="Send targeted updates to active subagents using `send_message` with their conversation ID.",
                code_template="""send_message(
    Recipient="conv-12345",
    Message="Focus search on index optimizations for user_id column."
)""",
                explanation="`send_message` enables real-time collaboration between parent agents and background subagents.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-7",
        title="7. Hooks & Custom Extensions",
        description="Attach custom hooks to lifecycle events like tool execution, agent initialization, or command finished.",
        icon="fa-plug",
        estimated_time="15 mins",
        labs=[
            LabTask(
                id="mod-7-lab-1",
                title="Lab 7.1: Pre-Tool Execution Hooks",
                instruction="Configure a pre-run hook to intercept and log shell commands before execution.",
                code_template="""# Example hook configuration:
hooks:
  pre_command:
    - action: log_audit
      target: "/tmp/cmd_audit.log"
""",
                explanation="Hooks allow developers to enforce enterprise compliance and logging on agent actions.",
            ),
        ],
    ),
    CurriculumModule(
        id="mod-8",
        title="8. Terminal Sandbox Security & Policies",
        description="Understand standard vs bypass sandbox execution modes, command prefix auto-approvals, and network isolation.",
        icon="fa-shield-alt",
        estimated_time="15 mins",
        labs=[
            LabTask(
                id="mod-8-lab-1",
                title="Lab 8.1: Sandbox Execution Modes & Best Practices",
                instruction="Differentiate between `BypassSandbox: false` (isolated) and `BypassSandbox: true` (host access).",
                code_template="""# Run sandboxed first (BypassSandbox: false):
run_command(CommandLine="pytest tests/", WaitMsBeforeAsync=5000)

# Switch to bypass ONLY if network/host access is strictly required:
run_command(CommandLine="pip install -r requirements.txt", BypassSandbox=True)""",
                explanation="Always attempt sandboxed execution first. Only escalate single commands that genuinely need network or elevated access.",
            ),
        ],
    ),
]

