import json
import os
import yaml
from pathlib import Path
from typing import List, Dict
from fastapi import APIRouter, HTTPException, status

from app.models import (
    CurriculumModule,
    ProgressUpdate,
    UserProgressResponse,
    AgentsConfigInput,
    SkillConfigInput,
    MCPConfigInput,
    ConfigGenerationResponse,
    ValidationRequest,
    ValidationResult,
    AssistantChatRequest,
    AssistantChatResponse,
)
from app.curriculum import CURRICULUM_MODULES
from app.validator import validate_config

import sys
AGY_AGENT_PATH = Path(__file__).resolve().parent.parent.parent.parent / "agy-agent"
if str(AGY_AGENT_PATH) not in sys.path:
    sys.path.insert(0, str(AGY_AGENT_PATH))

try:
    from agy_agent.service import assistant_service
except Exception:
    assistant_service = None

router = APIRouter(prefix="/api", tags=["api"])

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
PROGRESS_FILE = DATA_DIR / "user_progress.json"


def _get_progress_data() -> Dict[str, List[str]]:
    if not PROGRESS_FILE.exists():
        return {}
    try:
        with open(PROGRESS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _save_progress_data(data: Dict[str, List[str]]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(PROGRESS_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


@router.get("/curriculum", response_model=List[CurriculumModule])
def get_curriculum() -> List[CurriculumModule]:
    return CURRICULUM_MODULES


@router.get("/progress", response_model=UserProgressResponse)
def get_progress() -> UserProgressResponse:
    data = _get_progress_data()
    return UserProgressResponse(progress=data)


@router.post("/progress", response_model=UserProgressResponse)
def update_progress(update: ProgressUpdate) -> UserProgressResponse:
    data = _get_progress_data()
    data[update.module_id] = update.completed_labs
    _save_progress_data(data)
    return UserProgressResponse(progress=data)


@router.post("/generate/agents", response_model=ConfigGenerationResponse)
def generate_agents_config(input_data: AgentsConfigInput) -> ConfigGenerationResponse:
    custom_rules_str = "\n".join(
        [f"- {rule}" for rule in input_data.custom_rules if rule.strip()]
    )
    if custom_rules_str:
        custom_rules_str = f"\n\n## Custom Team Rules\n{custom_rules_str}"

    content = f"""# My AI Development Team Configuration

## Product Manager ({input_data.pm_name})
- Role: {input_data.pm_role}
- Behavior: Strict and detail-oriented. Must verify requirements before code is written.

## Engineer ({input_data.coder_name})
- Role: {input_data.coder_role}
- Behavior: Strictly adheres to the spec generated by {input_data.pm_name}.

## Quality Assurance ({input_data.qa_name})
- Role: {input_data.qa_role}
- Behavior: Reviews generated code, writes test suites, and reports explicit error tracebacks.{custom_rules_str}
"""
    return ConfigGenerationResponse(filename="AGENTS.md", content=content.strip())


@router.post("/generate/skill", response_model=ConfigGenerationResponse)
def generate_skill_config(input_data: SkillConfigInput) -> ConfigGenerationResponse:
    frontmatter_dict = {
        "name": input_data.name,
        "description": input_data.description,
    }
    if input_data.allowed_tools:
        frontmatter_dict["allowed_tools"] = input_data.allowed_tools

    frontmatter_yaml = yaml.dump(frontmatter_dict, sort_keys=False).strip()

    content = f"""---
{frontmatter_yaml}
---

# {input_data.name.replace('-', ' ').title()} Skill Instructions

{input_data.instructions}
"""
    filename = f"{input_data.name}/SKILL.md" if input_data.name else "SKILL.md"
    return ConfigGenerationResponse(filename=filename, content=content.strip())


@router.post("/generate/mcp", response_model=ConfigGenerationResponse)
def generate_mcp_config(input_data: MCPConfigInput) -> ConfigGenerationResponse:
    mcp_dict = {
        "mcpServers": {
            input_data.server_name: {
                "command": input_data.command,
                "args": input_data.args,
                "env": input_data.env_vars,
            }
        }
    }
    content = json.dumps(mcp_dict, indent=2)
    return ConfigGenerationResponse(filename="mcp.json", content=content)


@router.post("/validate", response_model=ValidationResult)
def validate_configuration(request: ValidationRequest) -> ValidationResult:
    return validate_config(request.config_type, request.content)


@router.post("/assistant/chat", response_model=AssistantChatResponse)
def assistant_chat(request: AssistantChatRequest) -> AssistantChatResponse:
    if not request.message.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="Message cannot be empty"
        )

    if assistant_service:
        result = assistant_service.answer_query(request.message, request.session_id)
        return AssistantChatResponse(**result)

    return AssistantChatResponse(
        response="Antigravity Assistant service is initializing. Please try again shortly.",
        source="System Fallback",
    )


@router.get("/assistant/suggestions", response_model=List[str])
def assistant_suggestions() -> List[str]:
    return [
        "How does /goal differ from /plan?",
        "Compare Antigravity with Cursor",
        "Generate .agents/AGENTS.md config for a 3-agent team",
        "What are custom skills in AGY and how do I create one?",
        "What is the /grill-me command and when should I use it?",
        "Explain the Terminal Sandbox and security permissions in AGY",
    ]
